name: Run n8n Workflow Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  run-n8n-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build the project
        run: npm run build

      - name: Link project for n8n
        run: |
          npm link
          mkdir -p ~/.n8n/custom/node_modules
          ln -s "$(pwd)" ~/.n8n/custom/node_modules/n8n-nodes-pgp

      - name: Install n8n
        run: npm install -g n8n

      - name: Create credentials file
        run: |
          echo "${{ secrets.N8N_CREDENTIALS }}" > tests/credentials/credentials.json

      - name: Execute Workflow
        env:
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
          N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
        run: |
          # Load credentials
          n8n import:credentials --input=tests/credentials/credentials.json

          # Execute all workflows in the tests/workflows directory
          for workflow in tests/workflows/*.json; do
            echo "Running workflow $workflow"
            n8n executeWorkflow --file=$workflow
          done
